### ISSUE TITLE
Exception while opening the app

### ISSUE THREAD

**Issue by imsanjaysah** [GauravMBansod/intellore_assignment#1]
I have noticed below exception while opening the app. Can you please fix the issue?

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: The following assertion was thrown building StreamBuilder<bool>(dirty, state:
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: _StreamBuilderBaseState<bool, AsyncSnapshot<bool>>#8cd49):
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: Failed assertion: boolean expression must not be null
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: The relevant error-causing widget was:
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter:   StreamBuilder<bool>
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter:   file:///D:/intellore_interview/CodingChallenge/GauravMBansod/intellore_assignment/lib/main.dart:138:15
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: When the exception was thrown, this was the stack:
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #0      _MyHomePageState.build.<anonymous closure> (package:intelloreassignment/main.dart:142:38)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #1      StreamBuilder.build (package:flutter/src/widgets/async.dart:509:81)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:127:48)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: ...     Normal element mounting (37 frames)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #49     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: ...     Normal element mounting (193 frames)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #242    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #243    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: ...     Normal element mounting (253 frames)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #496    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #497    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #498    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #499    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
2020-06-10 11:51:57.589 8886-9063/com.guarav.intelloreassignment I/flutter: #500    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
2020-06-10 11:51:57.590 8886-9063/com.guarav.intelloreassignment I/flutter: #501    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
2020-06-10 11:51:57.590 8886-9063/com.guarav.intelloreassignment I/flutter: #502    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
2020-06-10 11:51:57.590 8886-9063/com.guarav.intelloreassignment I/flutter: #503    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
2020-06-10 11:51:57.590 8886-9063/com.guarav.intelloreassignment I/flutter: #504    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
2020-06-10 11:51:57.590 8886-9063/com.guarav.intelloreassignment I/flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

**Comment by GauravMBansod** [comment]
let me check

**Comment by GauravMBansod** [comment]
issue solved
